// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXD7uusyJV6MgaWFhrWmIwh4_kQfBp30c',
    appId: '1:181567391284:web:b0c00c6784b0a2e0e36c61',
    messagingSenderId: '181567391284',
    projectId: 'poskeeper',
    authDomain: 'poskeeper.firebaseapp.com',
    storageBucket: 'poskeeper.appspot.com',
    measurementId: 'G-D3ENZXTR12',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtX4n7fssoZWQpDyE2iwpO4qL9lTjvzbM',
    appId: '1:181567391284:android:c2857153b89bd4f5e36c61',
    messagingSenderId: '181567391284',
    projectId: 'poskeeper',
    storageBucket: 'poskeeper.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD83YwwGtonoHnfiJNBhpodE83BiFlQr2o',
    appId: '1:181567391284:ios:6d58cc46ad0c58a2e36c61',
    messagingSenderId: '181567391284',
    projectId: 'poskeeper',
    storageBucket: 'poskeeper.appspot.com',
    iosBundleId: 'com.example.stormen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD83YwwGtonoHnfiJNBhpodE83BiFlQr2o',
    appId: '1:181567391284:ios:bd4ea22132737762e36c61',
    messagingSenderId: '181567391284',
    projectId: 'poskeeper',
    storageBucket: 'poskeeper.appspot.com',
    iosBundleId: 'com.example.stormen.RunnerTests',
  );
}
