// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmJSma6aInbd1ttcSBYG406Av7yJUIYjs',
    appId: '1:688643592050:web:adc4370365367d4b1017eb',
    messagingSenderId: '688643592050',
    projectId: 'stormenmain',
    authDomain: 'stormenmain.firebaseapp.com',
    storageBucket: 'stormenmain.appspot.com',
    measurementId: 'G-9CJ9DBSDSC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKKOqc2wbgs63gFHtsSC1i7ibHesPWoEo',
    appId: '1:688643592050:android:3c316125d6e41b101017eb',
    messagingSenderId: '688643592050',
    projectId: 'stormenmain',
    storageBucket: 'stormenmain.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXWunDXk3J4NA7V7DZ_CeoD3bUaaGTMYE',
    appId: '1:688643592050:ios:e94e0f69f051e89a1017eb',
    messagingSenderId: '688643592050',
    projectId: 'stormenmain',
    storageBucket: 'stormenmain.appspot.com',
    iosBundleId: 'com.example.stormen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXWunDXk3J4NA7V7DZ_CeoD3bUaaGTMYE',
    appId: '1:688643592050:ios:9c712650cecffb5d1017eb',
    messagingSenderId: '688643592050',
    projectId: 'stormenmain',
    storageBucket: 'stormenmain.appspot.com',
    iosBundleId: 'com.example.stormen.RunnerTests',
  );
}
